### ISSUE TITLE
add team to repo

### ISSUE THREAD

**Issue by wrgr** [openconnectome/AT-synapse-detection#1]
Need synaptome team added to AT-synapse-detection repo.

**Comment by jovo** [comment]
who's on it? send git handles

On Wednesday, April 15, 2015, William Gray notifications@github.com wrote:

>  Need synaptome team added to AT-synapse-detection repo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/AT-synapse-detection/issues/1.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
There is already a team called 'synaptome' - we just need that team added
to this repo.

Best,
Will

On Wed, Apr 15, 2015 at 6:20 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
done?

On Wed, Apr 15, 2015 at 6:22 PM, William Gray notifications@github.com
wrote:

>  There is already a team called 'synaptome' - we just need that team added
> to this repo.
> 
> Best,
> Will
> 
> On Wed, Apr 15, 2015 at 6:20 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > who's on it? send git handles
> > 
> > On Wednesday, April 15, 2015, William Gray notifications@github.com
> > wrote:
> > 
> > > Need synaptome team added to AT-synapse-detection repo.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/openconnectome/AT-synapse-detection/issues/1.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, my calendar
> > <
> > 
> > https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/AT-synapse-detection/issues/1#issuecomment-93585606
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/AT-synapse-detection/issues/1#issuecomment-93585846
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
